from ReceptionSystem.Page import *
from ReceptionSystem.Character import *
class Lowell(Character):
    def __init__(self,id,pos):
        liudice11=Dice(2,7,"Attack","Pierce",None,None)
        liudice12=Dice(1,2,"Attack","Pierce",None,None)

        liudice21=Dice(4,9,"Block","Block",None,None)
        liudice22=Dice(4,8,"Attack","Slash",None,None)

        liudice31=Dice(4,8,"Attack","Slash",None,None)
        liudice31.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice32=Dice(3,8,"Attack","Slash",None,None)
        liudice32.AddDiceBuff(HitExertBuffs(["Burn"],[1],False))

        liudice41=Dice(4,8,"Block","Block",None,None)
        liudice42=Dice(5,9,"Attack","Pierce",None,None)
        liudice42.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice43=Dice(4,9,"Attack","Slash",None,None)
        liudice43.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice44=Dice(3,7,"Block","Block",None,None,True)

        liudice51=Dice(8,20,"Attack","Slash",None,None)
        liudice51.AddDiceBuff(MassHitExertBuffs(["Burn"],[3],False))

        liupage1=Page(u"长驱直入","Melee",[],0,None,1,"Green")
        liupage1.AddPageBuff(UseLight(1))
        liupage1.AddDice(liudice11)
        liupage1.AddDice(liudice12)

        liupage2=Page(u"一决雌雄","Melee",[],1,None,1,"Blue")
        liupage2.AddPageBuff(UseGetGreenCoin())
        liupage2.AddDice(liudice21)
        liupage2.AddDice(liudice22)

        liupage3=Page(u"剑之所向","Melee",[],2,None,1,"Blue")
        liupage3.AddPageBuff(EmotionLevelDecost(3,1))
        liupage3.AddDice(liudice31)
        liupage3.AddDice(liudice32)

        liupage4=Page(u"慷慨激昂","Melee",[],3,None,1,"Gold")
        liupage4.AddPageBuff(EmotionPower())
        liupage4.AddDice(liudice41)
        liupage4.AddDice(liudice42)
        liupage4.AddDice(liudice43)
        liupage4.AddCounterDice(liudice44)

        liupage5=Page(u"燎原烈火","Individual",[],4,None,1,"Gold")
        liupage5.AddDice(liudice51)

        res={"Slash":1.0,"Pierce":0.5,"Blunt":1.0,"Slash_s":1.0,"Pierce_s":0.5,"Blunt_s":1.0}
        super().__init__(u"罗威尔",160,80,res,2,7,1,3,id,pos,"Enemy")
        self.AddPage(liupage1)
        self.AddPage(liupage1)
        self.AddPage(liupage2)
        self.AddPage(liupage2)
        self.AddPage(liupage3)
        self.AddPage(liupage3)
        self.AddPage(liupage4)
        self.AddPage(liupage4)
        self.AddPage(liupage5)
        self.AddPassive(u"速战速决3")
        self.AddPassive(u"所向无前")
        self.AddPassive(u"坚如磐石")
        self.AddPassive(u"常备不懈")
        self.AddPassive(u"满腔热血")
class Mei(Character):
    def __init__(self,id,pos):
        liudice11=Dice(2,7,"Attack","Pierce",None,None)
        liudice12=Dice(1,2,"Attack","Pierce",None,None)
        liupage1=Page(u"长驱直入","Melee",[],0,None,1,"Green")
        liupage1.AddPageBuff(UseLight(1))
        liupage1.AddDice(liudice11)
        liupage1.AddDice(liudice12)

        liudice21=Dice(4,9,"Block","Block",None,None)
        liudice22=Dice(4,8,"Attack","Slash",None,None)
        liupage2=Page(u"一决雌雄","Melee",[],1,None,1,"Blue")
        liupage2.AddPageBuff(UseGetGreenCoin())
        liupage2.AddDice(liudice21)
        liupage2.AddDice(liudice22)

        liudice41=Dice(4,8,"Block","Block",None,None)
        liudice42=Dice(5,9,"Attack","Pierce",None,None)
        liudice42.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice43=Dice(4,9,"Attack","Slash",None,None)
        liudice43.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice44=Dice(3,7,"Block","Block",None,None,True)
        liupage4=Page(u"慷慨激昂","Melee",[],3,None,1,"Gold")
        liupage4.AddPageBuff(EmotionPower())
        liupage4.AddDice(liudice41)
        liupage4.AddDice(liudice42)
        liupage4.AddDice(liudice43)
        liupage4.AddCounterDice(liudice44)

        liudice61=Dice(5,10,"Attack","Blunt",None,None)
        liudice61.AddDiceBuff(HitPage(1))
        liupage6=Page(u"神龍抬首","Melee",[],1,None,1,"Green")
        liupage6.AddDice(liudice61)

        liudice71=Dice(4,9,"Block","Block",None,None)
        liudice72=Dice(6,10,"Attack","Slash",None,None)
        liupage7=Page(u"碧血丹心","Melee",[],2,None,1,"Purple")
        liupage7.AddPageBuff(UseGetGreenCoin())
        liupage7.AddDice(liudice71)
        liupage7.AddDice(liudice72)

        liudice81=Dice(5,6,"Attack","Pierce",None,None)
        liudice82=Dice(8,21,"Attack","Blunt",None,None)
        liudice82.AddDiceBuff(HitExertEmotionBuff("Burn",False))
        liudice83=Dice(3,7,"Attack","Pierce",None,None,True)
        liupage8=Page(u"铁山靠","Melee",[],3,None,1,"Gold")
        liupage8.AddDice(liudice81)
        liupage8.AddDice(liudice82)
        liupage8.AddCounterDice(liudice83)

        res={"Slash":1.0,"Pierce":0.5,"Blunt":1.0,"Slash_s":1.0,"Pierce_s":1.0,"Blunt_s":0.5}
        super().__init__(u"梅",140,70,res,2,6,1,3,id,pos,"Enemy")
        self.AddPage(liupage1)
        self.AddPage(liupage1)
        self.AddPage(liupage2)
        self.AddPage(liupage2)
        self.AddPage(liupage6)
        self.AddPage(liupage6)
        self.AddPage(liupage7)
        self.AddPage(liupage4)
        self.AddPage(liupage8)
        self.AddPassive(u"速战速决")
        self.AddPassive(u"常备不懈")
        self.AddPassive(u"满腔热血")
class LiuFixer(Character):
    def __init__(self,id,pos):
        liudice11=Dice(2,7,"Attack","Pierce",None,None)
        liudice12=Dice(1,2,"Attack","Pierce",None,None)
        liupage1=Page(u"长驱直入","Melee",[],0,None,1,"Green")
        liupage1.AddPageBuff(UseLight(1))
        liupage1.AddDice(liudice11)
        liupage1.AddDice(liudice12)

        liudice21=Dice(4,9,"Block","Block",None,None)
        liudice22=Dice(4,8,"Attack","Slash",None,None)
        liupage2=Page(u"一决雌雄","Melee",[],1,None,1,"Blue")
        liupage2.AddPageBuff(UseGetGreenCoin())
        liupage2.AddDice(liudice21)
        liupage2.AddDice(liudice22)

        liudice31=Dice(4,8,"Attack","Slash",None,None)
        liudice31.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice32=Dice(3,8,"Attack","Slash",None,None)
        liudice32.AddDiceBuff(HitExertBuffs(["Burn"],[1],False))
        liupage3=Page(u"剑之所向","Melee",[],2,None,1,"Blue")
        liupage3.AddPageBuff(EmotionLevelDecost(3,1))
        liupage3.AddDice(liudice31)
        liupage3.AddDice(liudice32)

        liudice41=Dice(4,8,"Block","Block",None,None)
        liudice42=Dice(5,9,"Attack","Pierce",None,None)
        liudice42.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice43=Dice(4,9,"Attack","Slash",None,None)
        liudice43.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liudice44=Dice(3,7,"Block","Block",None,None,True)
        liupage4=Page(u"慷慨激昂","Melee",[],3,None,1,"Gold")
        liupage4.AddPageBuff(EmotionPower())
        liupage4.AddDice(liudice41)
        liupage4.AddDice(liudice42)
        liupage4.AddDice(liudice43)
        liupage4.AddCounterDice(liudice44)

        liudice71=Dice(4,9,"Block","Block",None,None)
        liudice72=Dice(6,10,"Attack","Slash",None,None)
        liupage7=Page(u"碧血丹心","Melee",[],2,None,1,"Purple")
        liupage7.AddPageBuff(UseGetGreenCoin())
        liupage7.AddDice(liudice71)
        liupage7.AddDice(liudice72)

        liudice91=Dice(3,7,"Attack","Blunt",None,None)
        liudice91.AddDiceBuff(ReduceDefensePower(2))
        liudice92=Dice(3,7,"Attack","Pierce",None,None)
        liudice92.AddDiceBuff(HitExertBuffs(["Burn"],[1],False))
        liupage9=Page(u"破竹之势","Melee",[],1,None,1,"Blue")
        liupage9.AddPageBuff(RoundAttackDamageBuff(1))
        liupage9.AddDice(liudice91)
        liupage9.AddDice(liudice92)

        liudiceA1=Dice(2,6,"Evade","Evade",None,None)
        liudiceA2=Dice(4,8,"Attack","Pierce",None,None)
        liudiceA2.AddDiceBuff(HitGetBuffs(["Haste"],[1]))
        liudiceA3=Dice(3,8,"Attack","Pierce",None,None)
        liudiceA3.AddDiceBuff(HitGetBuffs(["Haste"],[1]))
        liupageA=Page(u"刀光剑影","Melee",[],2,None,1,"Green")
        liupageA.AddPageBuff(UseGetGreenCoin())
        liupageA.AddDice(liudiceA1)
        liupageA.AddDice(liudiceA2)
        liupageA.AddDice(liudiceA3)

        liudiceB1=Dice(3,10,"Evade","Evade",None,None)
        liudiceB2=Dice(8,17,"Block","Block",None,None)
        liudiceB2.AddDiceBuff(WinPage(1))
        liudiceB3=Dice(3,6,"Attack","Pierce",None,None)
        liudiceB3.AddDiceBuff(HitExertBuffs(["Burn"],[2],False))
        liupageB=Page(u"牢不可破","Melee",[],3,None,1,"Purple")
        liupageB.AddPageBuff(UsePage(1))
        liupageB.AddDice(liudiceB1)
        liupageB.AddDice(liudiceB2)
        liupageB.AddDice(liudiceB3)

        res={"Slash":1.0,"Pierce":0.5,"Blunt":1.0,"Slash_s":1.0,"Pierce_s":1.0,"Blunt_s":1.0}
        super().__init__(u"六协会2科收尾人",120,60,res,2,6,1,3,id,pos,"Enemy")
        self.AddPage(liupage1)
        self.AddPage(liupage1)
        self.AddPage(liupage9)
        self.AddPage(liupage2)
        self.AddPage(liupage3)
        self.AddPage(liupageA)
        self.AddPage(liupage7)
        self.AddPage(liupage4)
        self.AddPage(liupageB)
        self.AddPassive(u"速战速决")
        self.AddPassive(u"满腔热血")